#pinned to known working older sha version
FROM python:3.13-slim@sha256:60df8d213797a669b8c4899424acca844f1e476295d4a2d058713dc3deeb504c

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    netcat-openbsd \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/requirements.txt

#pinned to known working version 
RUN pip install setuptools==75.3.1
RUN pip install -r requirements.txt

COPY . /app/

CMD ["bash", "/app/startup.sh"]
