FROM node:lts-alpine3.23@sha256:d1b3b4da11eefd5941e7f0b9cf17783fc99d9c6fc34884a665f40a06dbdfc94f AS asset-env

WORKDIR /app

COPY nginx/assets .

RUN yarn  --immutable --frozen-lockfile --ignore-scripts && yarn build

FROM nginx:stable-alpine

COPY nginx/default.conf.template /etc/nginx/templates/default.conf.template
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY opgincidentresponse/static /app/opgincidentresponse/static
COPY --from=node /home/node /app/opgincidentresponse/static
COPY --from=asset-env /app/dist /app/opgincidentresponse/static

ENV TIMEOUT=20
