FROM python:3.14-slim@sha256:0097bb60d0c7a2c6af5a56e747eabc2016218f837f76daa70b9526fb883bc499

RUN apt-get update && apt-get install -y --no-install-recommends \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.11.21 /uv /uvx /bin/
ENV UV_MALWARE_CHECK=1
ENV UV_SYSTEM_PYTHON=1

WORKDIR /app

COPY pyproject.toml /app/pyproject.toml
COPY uv.lock /app/uv.lock

RUN uv sync --frozen

COPY tests /app/tests
COPY testcfg /app/testcfg
COPY opgincidentresponse /app/opgincidentresponse
COPY response /app/response
COPY pytest.ini /app/pytest.ini
COPY manage.py /app/manage.py

CMD ["uv", "run", "pytest"]
