#pinned to known working older sha version
FROM python:3.13-slim@sha256:d97b595c5f4ac718102e5a5a91adaf04b22e852961a698411637c718d45867c8

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    netcat-openbsd \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/requirements.txt

#pinned to known working version 
RUN pip install setuptools==75.3.1
RUN pip install -r requirements.txt

COPY . /app/

CMD ["bash", "/app/startup.sh"]
