FROM python:3.14-slim@sha256:584e89d31009a79ae4d9e3ab2fba078524a6c0921cb2711d05e8bb5f628fc9b9

RUN apt-get update && apt-get install -y --no-install-recommends \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY tests /app/tests
COPY testcfg /app/testcfg
COPY response /app/response
COPY requirements.txt /app/requirements.txt
COPY requirements-dev.txt /app/requirements-dev.txt
COPY pytest.ini /app/pytest.ini
COPY manage.py /app/manage.py

RUN pip install --upgrade setuptools
RUN pip install -r requirements-dev.txt

CMD [ "pytest"]