FROM python:3.14-slim@sha256:3353bb7e9ae99c7cce6cad2b2f2b174e8f22813ac43e3b13e7a742627d2b01d8

RUN apt-get update && apt-get install -y --no-install-recommends \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.11.21 /uv /uvx /bin/
ENV UV_MALWARE_CHECK=1
ENV UV_SYSTEM_PYTHON=1

WORKDIR /app

COPY pyproject.toml /app/pyproject.toml
COPY uv.lock /app/uv.lock

RUN uv sync --frozen

COPY tests /app/tests
COPY testcfg /app/testcfg
COPY opgincidentresponse /app/opgincidentresponse
COPY response /app/response
COPY pytest.ini /app/pytest.ini
COPY manage.py /app/manage.py

CMD ["uv", "run", "pytest"]
