FROM node:lts-alpine3.23@sha256:931d7d57f8c1fd0e2179dbff7cc7da4c9dd100998bc2b32afc85142d8efbc213 AS asset-env

WORKDIR /app

COPY nginx/assets .

RUN yarn  --immutable --frozen-lockfile --ignore-scripts && yarn build

FROM nginx:stable-alpine

COPY nginx/default.conf.template /etc/nginx/templates/default.conf.template
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY opgincidentresponse/static /app/opgincidentresponse/static
COPY --from=node /home/node /app/opgincidentresponse/static
COPY --from=asset-env /app/dist /app/opgincidentresponse/static

ENV TIMEOUT=20
