# Generated by Django 2.2.12 on 2020-10-23 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('response', '0016_actions_auto_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuspage_incident_id', models.CharField(max_length=100, null=True, unique=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='response.Incident')),
            ],
        ),
    ]
