# Generated by Django 2.2.12 on 2020-10-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgincidentresponse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagerDutySpecialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('summary', models.TextField(max_length=1000)),
                ('escalation_policy', models.CharField(max_length=10)),
            ],
        ),
    ]
