name: "[Test] Run Unit Tests"

defaults:
  run:
    shell: bash

on:
  workflow_call:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: "0"
      - run: make test
